### ISSUE TITLE
Menghilangkan Kode yg Tidak Digunakan

### ISSUE THREAD

**Issue by jefrydco** [fadhlisy/spa-vuejs-fundamental#2]
Hi Mas Fadhli, terima kasih sudah mengirimkan kode belajar Vue.js Fundamental, saya sangat mengapresiasi kerja keras Mas Fahdli.

Mas juga sudah menggunakan Bootstrap untuk menerapkan gayanya, selain itu saya lihat Mas membuat `methods` untuk menampilkan waktu dengan logika yg menurut saya cukup kompleks. Luas biasa Mas! Saya memiliki beberapa saran untuk kode yg Mas kirimkan

1. Memindahkan Fungsi `time` Menjadi Properti Penghitung
Untuk lebih mengoptimalkan kode, Mas dapat memindahkan fungsi `time` menjadi properti penghitung Mas. Hasil dari properti penghitung akan di _cache_ sehingga jika nilai parameter yg dimasukkan pada fungsi tersebut sama dan sudah pernah dikalkulasi, Vue.js akan mengembalikan nilai yg sama juga. Kurang lebih jika fungsi `time` tersebut diubah menjadi properti penghitung hasilnya akan seperti berikut Mas:

```javascript
export default {
  computed: {
    time() {
      return (start) => {
        // Kode fungsi `time`
      }
    }
  }
}
```

Lebih lengkap Mas dapat membacanya pada dokumentasi resmi Vue.js berikut [Dokumentasi Vue.js Bahasa Indonesia - Penyimpanan Penghitung vs Metode](https://docs.vuejs.id/v2/guide/computed.html#Penyimpanan-Penghitung-Computed-Cache-vs-Metode)

2. Menghilangkan Kode yg Tidak Digunakan
Pada berkas `index.html` pada baris 9-12 berikut:
https://github.com/fadhlisy/spa-vuejs-fundamental/blob/28d51781e01959f4db9508af1137ef3703a2ebb2/index.html#L9-L12
Mas mencantumkan beberapa kerangka kerja JavaScript eksternal yg sepertinya tidak Mas gunakan, jadi saran saya untuk kode tersebut bisa dihilangkan Mas. Untuk Bootstrap Mas sepertinya hanya perlu CSS nya saja Mas.

Semangat Mas! 😄

**Comment by fadhlisy** [comment]
Sudah dibenahi kak, tp untuk script font awesome memang saya pakai, jadi nggak saya hilangin.
